FROM node:24-alpine AS builder

ARG DOCUSAURUS_CONF_URL='http://localhost:80'
ARG DOCKER_IMAGE_TAG='local'

WORKDIR /app
COPY package.json package-lock.json ./
RUN npm config delete proxy; npm config delete https-proxy; npm ci
COPY . .
RUN npm run build

FROM nginx:mainline-alpine-slim

COPY nginx/security-headers.conf /etc/nginx/security-headers.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html
