FROM node:alpine as builder

ARG DOCUSAURUS_CONF_URL='http://localhost:80'
ARG DOCKER_IMAGE_TAG='local'

COPY . .
RUN npm install
RUN npm run build

FROM nginx:mainline-alpine-slim

COPY --from=builder /build /usr/share/nginx/html